# Default profile for advertising domain
# This is a baseline configuration that other profiles can extend
# See docs/profiles.md for full configuration options

profile_name: "default"
description: "Default advertising industry monitoring profile"

# Entity focus - all entities at equal priority
# Override in specific profiles to prioritize certain companies
focus:
  holding_companies:
    priority_1: []  # Most important (e.g., WPP, OMC)
    priority_2: []  # Secondary importance
    priority_3: []  # Tertiary
    exclude: []     # Companies to ignore

  agency_types:
    primary: [creative, media]
    secondary: [technology, ad_tech]
    tertiary: [entertainment, talent, pr, production]

  geographic:
    - United States
    - United Kingdom
    - Global

# Thought leaders - domain defaults (can be overridden)
thought_leaders:
  - name: "Scott Galloway"
    x_handle: "profgalloway"
    priority: 1
  - name: "Seth Godin"
    x_handle: "ThisIsSethsBlog"
    priority: 2

# Publications to monitor (subset of domain.yaml publications)
publications:
  - Ad Age
  - AdWeek
  - Campaign
  - The Drum
  - Marketing Week
  - Digiday

# Reports to generate
reports:
  daily_brief: true
  weekly_digest: true
  fundraising: false

# Keywords for relevance scoring
keywords:
  boost: []   # Terms that increase item relevance
  filter: []  # Terms that decrease item relevance

# Collection depth per report type
# Options: quick (fewer items, faster), default, deep (more items, slower)
depth:
  daily: default
  weekly: default

# Delivery settings (override per profile)
delivery:
  channel: console  # console | file | email
  fallback: null

# LLM enhancement (disabled by default, enable in specific profiles)
llm:
  enabled: false
  mode: auto  # auto | openclaw | claude_cli | anthropic | disabled
